# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# MQTT Integration
mqtt:
  light:
    - name: "smartlamp-smartglow"
      state_topic: "smartlamp/smartglow/state"
      command_topic: "smartlamp/smartglow/state"
      brightness_state_topic: "smartlamp/smartglow/brightness"
      brightness_command_topic: "smartlamp/smartglow/brightness"
      brightness_scale: 100
      rgb_state_topic: "smartlamp/smartglow/color"
      rgb_command_topic: "smartlamp/smartglow/color"
      effect_state_topic: "smartlamp/smartglow/effect"
      effect_command_topic: "smartlamp/smartglow/effect"
      effect_list:
        - Static
        - Breath
        - Rainbow
        - Chase
        - Blink
        - Wave
      json_attributes_topic: "smartlamp/smartglow/color_name"
      optimistic: false
      qos: 0

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml